### ISSUE TITLE
A sample use for the Data formulation

### ISSUE THREAD

**Issue by MohSamNaf** [Armanfard-Lab/EEG-CGS#2]
Hello Narges

Thank you for sharing your code publicly. The quality of effort is tremendous and the research topic is very interesting.

I would like to know if you can provide some explanation about the data formulation in this class:
```
class formulateData(Dataset):
    def __init__(self, sampled_dir, raw_dir, time_step_size=1, clip_len=60, is_std=True, scaler=None,
                 split='train', adj_mat_dir=None, graph_type=None, top_edges=None, sampl_ratio=1, seed=42, fft_dir=None):
        self.sampled_dir = sampled_dir # H5 dir
        self.raw_dir = raw_dir # edf dir
        self.time_step_size = time_step_size # int, (s)
        self.clip_len = clip_len # clip size (s)
        self.is_std = is_std # z-normalize in the training set
        self.scaler = scaler # for std
        self.split = split # train or test
        self.adj_mat_dir = adj_mat_dir # pre-computed adjacent matrix only available for Dist graphs (from Tang et al. 2022)
        self.graph_type = graph_type # Dist/Rand/Corr/DTF
        self.top_edges = top_edges # int, Corr/DTF
        self.sampl_ratio = sampl_ratio # ratio of positive to negative samples
        self.fft_dir = fft_dir # fft dir
        self.edf_files = []
```

May you provide more information about `top_edges `? What is the difference in the effect of choosing Corr/DTF if it does not match the `graph_type `? For example selecting `graph_type = "Corr"`, but `top_edges = "DTF"`.

Additionally, quoted from your paper:
> We only keep the top three edges (i.e., m = 3)
> for each node to avoid overly connected graphs

May I ask why the only 3 top edges? Are you following the same value that has been suggested in Tang et. al, 2022?

Thank you for your time.

**Comment by Armanfard-Lab** [comment]
Hi,
Thanks for your interest in our work. We set top_edges as a hyperparameter for only Corr and DTF graph types. Following the literature in the graph theory and Tang et al. 2022, we set top_edges to 3, i.e.,  only three edges are kept for each node to preserve the high correlations between that node and other remaining nodes in the graph.

> Hello Narges
> 
> Thank you for sharing your code publicly. The quality of effort is tremendous and the research topic is very interesting.
> 
> I would like to know if you can provide some explanation about the data formulation in this class:
> 
> ```
> class formulateData(Dataset):
>     def __init__(self, sampled_dir, raw_dir, time_step_size=1, clip_len=60, is_std=True, scaler=None,
>                  split='train', adj_mat_dir=None, graph_type=None, top_edges=None, sampl_ratio=1, seed=42, fft_dir=None):
>         self.sampled_dir = sampled_dir # H5 dir
>         self.raw_dir = raw_dir # edf dir
>         self.time_step_size = time_step_size # int, (s)
>         self.clip_len = clip_len # clip size (s)
>         self.is_std = is_std # z-normalize in the training set
>         self.scaler = scaler # for std
>         self.split = split # train or test
>         self.adj_mat_dir = adj_mat_dir # pre-computed adjacent matrix only available for Dist graphs (from Tang et al. 2022)
>         self.graph_type = graph_type # Dist/Rand/Corr/DTF
>         self.top_edges = top_edges # int, Corr/DTF
>         self.sampl_ratio = sampl_ratio # ratio of positive to negative samples
>         self.fft_dir = fft_dir # fft dir
>         self.edf_files = []
> ```
> 
> May you provide more information about `top_edges `? What is the difference in the effect of choosing Corr/DTF if it does not match the `graph_type `? For example selecting `graph_type = "Corr"`, but `top_edges = "DTF"`.
> 
> Additionally, quoted from your paper:
> 
> > We only keep the top three edges (i.e., m = 3)
> > for each node to avoid overly connected graphs
> 
> May I ask why the only 3 top edges? Are you following the same value that has been suggested in Tang et. al, 2022?
> 
> Thank you for your time.

**Comment by MohSamNaf** [comment]
Thank you for your quick reply. Much appreciated
