### ISSUE TITLE
train_small_60s_sz.txt file

### ISSUE THREAD

**Issue by Yaoyux** [Armanfard-Lab/EEG-CGS#5]
I have a question regarding the data/small_file_markers/train_small_60s_sz.txt file.I noticed that this file is referenced, but I couldn’t find it in the dataset. Could you please clarify the purpose of this file and how it is generated or obtained? Any guidance on this would be greatly appreciated.

**Comment by xihaopark** [comment]
Hi Yaoyux! I have the same question as you. Have you been able to find a way to fix this? I would appreciate it if you could share some information with me.
